mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxies:
  - {"name":"dongtaiwang.com_1","type":"vmess","server":"23.227.39.12","port":8080,"cipher":"auto","uuid":"80b48bc6-1faa-41f5-91f8-0bce015a8bea","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"uh-lawyers-instruments-kernel.trycloudflare.com","network":"ws","ws-opts":{"path":"80b48bc6-1faa-41f5-91f8-0bce015a8bea-vm","headers":{"host":"uh-lawyers-instruments-kernel.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_2","type":"vmess","server":"yh1.freeh1.xyz","port":8080,"cipher":"auto","uuid":"80b48bc6-1faa-41f5-91f8-0bce015a8bea","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"uh-lawyers-instruments-kernel.trycloudflare.com","network":"ws","ws-opts":{"path":"80b48bc6-1faa-41f5-91f8-0bce015a8bea-vm","headers":{"host":"uh-lawyers-instruments-kernel.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_3","type":"vmess","server":"23.227.39.12","port":8080,"cipher":"auto","uuid":"d4534b81-2c40-48a2-9a7b-35cd958c7437","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"uh-lawyers-instruments-kernel.trycloudflare.com","network":"ws","ws-opts":{"path":"d4534b81-2c40-48a2-9a7b-35cd958c7437-vm","headers":{"host":"uh-lawyers-instruments-kernel.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_4","type":"vmess","server":"fbi.gov","port":8080,"cipher":"auto","uuid":"bdce8656-2802-4470-8946-ef3cf5244aa6","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"pcs-referenced-camera-concerns.trycloudflare.com","network":"ws","ws-opts":{"path":"bdce8656-2802-4470-8946-ef3cf5244aa6-vm","headers":{"host":"pcs-referenced-camera-concerns.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_5","type":"vmess","server":"yh1.freeh1.xyz","port":8080,"cipher":"auto","uuid":"c575b66a-2901-4e05-a4b2-453e196f9bb5","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"per-essex-patterns-bowling.trycloudflare.com","network":"ws","ws-opts":{"path":"c575b66a-2901-4e05-a4b2-453e196f9bb5-vm","headers":{"host":"per-essex-patterns-bowling.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_6","type":"vmess","server":"fbi.gov","port":8080,"cipher":"auto","uuid":"f4778b63-0daf-494e-8325-3660abc29384","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"bibliographic-sword-sequence-advertisers.trycloudflare.com","network":"ws","ws-opts":{"path":"f4778b63-0daf-494e-8325-3660abc29384-vm","headers":{"host":"bibliographic-sword-sequence-advertisers.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_7","type":"vmess","server":"23.227.39.24","port":8080,"cipher":"auto","uuid":"c575b66a-2901-4e05-a4b2-453e196f9bb5","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"per-essex-patterns-bowling.trycloudflare.com","network":"ws","ws-opts":{"path":"c575b66a-2901-4e05-a4b2-453e196f9bb5-vm","headers":{"host":"per-essex-patterns-bowling.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_8","type":"vmess","server":"23.227.39.23","port":8080,"cipher":"auto","uuid":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"configured-creek-relating-theater.trycloudflare.com","network":"ws","ws-opts":{"path":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3-vm","headers":{"host":"configured-creek-relating-theater.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_9","type":"vmess","server":"fbi.gov","port":8080,"cipher":"auto","uuid":"693da022-8e1f-4dab-b3ac-556321989f17","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"nest-emily-healing-h.trycloudflare.com","network":"ws","ws-opts":{"path":"693da022-8e1f-4dab-b3ac-556321989f17-vm","headers":{"host":"nest-emily-healing-h.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_10","type":"vmess","server":"yh1.freeh1.xyz","port":8080,"cipher":"auto","uuid":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"championship-bidding-oxygen-brochure.trycloudflare.com","network":"ws","ws-opts":{"path":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3-vm","headers":{"host":"championship-bidding-oxygen-brochure.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_11","type":"vmess","server":"23.227.39.23","port":8080,"cipher":"auto","uuid":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"championship-bidding-oxygen-brochure.trycloudflare.com","network":"ws","ws-opts":{"path":"46958ae9-31fb-48ef-8d13-9de4ac8a57b3-vm","headers":{"host":"championship-bidding-oxygen-brochure.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_12","type":"vmess","server":"23.227.39.45","port":8080,"cipher":"auto","uuid":"a984d860-a48a-4b1f-b6d4-74f7365b63e5","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"widescreen-instruction-breakdown-postage.trycloudflare.com","network":"ws","ws-opts":{"path":"a984d860-a48a-4b1f-b6d4-74f7365b63e5-vm","headers":{"host":"widescreen-instruction-breakdown-postage.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_13","type":"vmess","server":"yh1.freeh1.xyz","port":8080,"cipher":"auto","uuid":"a984d860-a48a-4b1f-b6d4-74f7365b63e5","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"widescreen-instruction-breakdown-postage.trycloudflare.com","network":"ws","ws-opts":{"path":"a984d860-a48a-4b1f-b6d4-74f7365b63e5-vm","headers":{"host":"widescreen-instruction-breakdown-postage.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_14","type":"vmess","server":"fbi.gov","port":8080,"cipher":"auto","uuid":"fbacc445-fe1c-4122-a2dd-c28c733ea043","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"larger-marketing-amounts-skin.trycloudflare.com","network":"ws","ws-opts":{"path":"fbacc445-fe1c-4122-a2dd-c28c733ea043-vm","headers":{"host":"larger-marketing-amounts-skin.trycloudflare.com"}}}
  - {"name":"H1","type":"hysteria","server":"www.dtku40.xyz","port":18490,47000-48000",sni":"paypal.com","skip-cert-verify":true,"alpn":["h3"],"protocol":"udp","auth_str":"dongtaiwang.com","up":11,"down":55,"hop_interval": 120}
  - {"name":"H2","type":"hysteria","server":"173.234.25.52","port":30072,47000-48000",sni":"paypal.com","skip-cert-verify":true,"alpn":["h3"],"protocol":"udp","auth_str":"dongtaiwang.com","up":11,"down":55,"hop_interval": 120}
  - {"name":"H3","type":"hysteria","server":"173.234.25.52","port":48919,47000-48000",sni":"paypal.com","skip-cert-verify":true,"alpn":["h3"],"protocol":"udp","auth_str":"dongtaiwang.com","up":11,"down":55,"hop_interval": 120}
  - {"name":"H4","type":"hysteria","server":"167.160.91.115","port":41189,47000-48000",sni":"paypal.com","skip-cert-verify":true,"alpn":["h3"],"protocol":"udp","auth_str":"bWAwIqINo7XDm1fUlXQGBifVIXoYs1ylgVKqWFKzK1XyDKuwNF","up":11,"down":55,"hop_interval": 120}
  - {"name":"H5","type":"hysteria","server":"51.158.54.46","port":55396,47000-48000",sni":"paypal.com","skip-cert-verify":true,"alpn":["h3"],"protocol":"udp","auth_str":"dongtaiwang.com","up":11,"down":55,"hop_interval": 120}
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
      - dongtaiwang.com_10
      - dongtaiwang.com_11
      - dongtaiwang.com_12
      - dongtaiwang.com_13
      - dongtaiwang.com_14
      - H1
      - H2
      - H3
      - H4
      - H5
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
      - dongtaiwang.com_10
      - dongtaiwang.com_11
      - dongtaiwang.com_12
      - dongtaiwang.com_13
      - dongtaiwang.com_14
      - H1
      - H2
      - H3
      - H4
      - H5
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,apache.org,PROXY
  - DOMAIN,skywalking.apache.org,PROXY
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
